// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSongToPlaylist(arg1, arg2) {
  return window['go']['main']['App']['AddSongToPlaylist'](arg1, arg2);
}

export function CreatePlaylist(arg1) {
  return window['go']['main']['App']['CreatePlaylist'](arg1);
}

export function CreatePlaylistFromExportify(arg1, arg2) {
  return window['go']['main']['App']['CreatePlaylistFromExportify'](arg1, arg2);
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function GetPlaylistState() {
  return window['go']['main']['App']['GetPlaylistState']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportExportify(arg1, arg2) {
  return window['go']['main']['App']['ImportExportify'](arg1, arg2);
}

export function NextSong() {
  return window['go']['main']['App']['NextSong']();
}

export function PlayPlaylist(arg1, arg2) {
  return window['go']['main']['App']['PlayPlaylist'](arg1, arg2);
}

export function PlaySong(arg1) {
  return window['go']['main']['App']['PlaySong'](arg1);
}

export function PrevSong() {
  return window['go']['main']['App']['PrevSong']();
}

export function RemoveSongFromPlaylist(arg1, arg2) {
  return window['go']['main']['App']['RemoveSongFromPlaylist'](arg1, arg2);
}

export function ReorderSong(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderSong'](arg1, arg2, arg3);
}

export function SeekBackward() {
  return window['go']['main']['App']['SeekBackward']();
}

export function SeekForward() {
  return window['go']['main']['App']['SeekForward']();
}

export function SeekTo(arg1) {
  return window['go']['main']['App']['SeekTo'](arg1);
}

export function SetPlaylistAlbumArt(arg1, arg2) {
  return window['go']['main']['App']['SetPlaylistAlbumArt'](arg1, arg2);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function ToggleLoop() {
  return window['go']['main']['App']['ToggleLoop']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
