// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSongToPlaylist(arg1:number,arg2:string):Promise<main.PlaylistState>;

export function CreatePlaylist(arg1:string):Promise<main.PlaylistState>;

export function CreatePlaylistFromExportify(arg1:string,arg2:string):Promise<main.PlaylistState>;

export function DeletePlaylist(arg1:number):Promise<main.PlaylistState>;

export function GetPlaylistState():Promise<main.PlaylistState>;

export function GetState():Promise<main.PlayerState>;

export function ImportExportify(arg1:number,arg2:string):Promise<main.PlaylistState>;

export function NextSong():Promise<string>;

export function PlayPlaylist(arg1:number,arg2:number):Promise<string>;

export function PlaySong(arg1:string):Promise<string>;

export function PrevSong():Promise<string>;

export function RemoveSongFromPlaylist(arg1:number,arg2:number):Promise<main.PlaylistState>;

export function ReorderSong(arg1:number,arg2:number,arg3:number):Promise<main.PlaylistState>;

export function SeekBackward():Promise<string>;

export function SeekForward():Promise<string>;

export function SeekTo(arg1:number):Promise<string>;

export function SetPlaylistAlbumArt(arg1:number,arg2:string):Promise<main.PlaylistState>;

export function SetVolume(arg1:number):Promise<string>;

export function Stop():Promise<void>;

export function ToggleLoop():Promise<string>;

export function TogglePause():Promise<string>;
